---
title: "NetDECODE demo"
author: "Shahin Mohammadi"
date: "April 1, 2019"
output: html_document
---

# Import expression matrix and convert it to an SCE object
```{r message=FALSE, warning=FALSE}
require(Matrix)
require(scater)
require(igraph)

# Load expression profile
sce = readRDS('reduced_sce.RDS')

S = sce@assays[["logcounts"]]
Labels = sce$Labels
  
require(NetDECODE)
require(ACTIONet)

```


## Pairwise co-observability/activity of gene pairs
```{r}
logPvals = asssessCoactivity(S)

# Use CD19 as a probe

row = match("CD19", rownames(sce))
gene.order = order(logPvals[row, ], decreasing = TRUE)

rownames(sce)[gene.order[1:20]]


```

## Sparsify and construct a graph
```{r}
Adj.dir = constructKstarNN(logPvals)
Adj = symmetrizeNetwork(Adj.dir)

# ## Network-enhancement
# A = as(Adj, 'dgTMatrix')
# eps = 1e-16
# rs = Matrix::rowSums(A)
# P = sparseMatrix(i = A@i+1, j = A@j+1, x = A@x/rs[A@i+1], dims = dim(A))  
# 
# # Transition field
# w = sqrt(Matrix::colSums(P)+eps)
# W = P %*% Matrix::Diagonal(x = 1/w, n = length(w))
# Adj = W %*% Matrix::t(W)

require(igraph)
G = graph_from_adjacency_matrix(as(symmetrizeNetwork(Adj), 'sparseMatrix'), mode = "undirected", weighted = TRUE)
clusters = cluster_louvain(G)$membership

counts = table(clusters)


modules = lapply(names(counts)[counts >= 30], function(x) {
  mask = clusters %in% x
  subAdj = G[mask, mask]
  subG = graph_from_adjacency_matrix(subAdj, weighted = TRUE, mode = "undirected")
  V(subG)$name = rownames(sce)[mask]
  return(subG)
})

Sorted.genes = lapply(modules, function(g) {
  pr = page_rank(g)$vector
  perm = order(pr, decreasing = TRUE)
  sorted.genes = V(g)$name[perm]
  print(sorted.genes[1:10])
  return(sorted.genes)
})

```

## Use network context to predict pvalue of activity
```{r}
markers = c("CD79A", "CD14", "GZMB", "CD3G")
cols = 1:ncol(sce)
rows = match(markers, rownames(sce))
activity.scores = t(predictActivityScores(S, rows, cols, Adj.dir))
colnames(activity.scores) = markers

df = as.data.frame(activity.scores)
df$celltype = sce$Labels

df = reshape2::melt(df)
colnames(df) = c("celltype", "gene", "value")

require(ggpubr)
ggbarplot(df, x = "celltype", y = "value", color = "gene", fill = "gene", position = position_dodge(0.9))


```

